language:
  - cpp

compiler:
  - gcc
  - clang

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - valgrind
      - lcov

before_install:
  # C++14, even C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14, even C++17
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - pip install codecov


script:
  # Build
  - mkdir build
  - cd build
  - cmake -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . --config Debug

  # Run test
  - ./../bin/wepp_test

  #- cd ../bin/
  #- valgrind --leak-check=full --track-origins=yes --error-exitcode=1 ./test

after_success:
  - lcov --directory ./CMakeFiles/wepp.dir --capture --output-file coverage.info
  # filter out system and extra files.
  # To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  # output coverage data for debugging (optional)
  - lcov --list coverage.info
  # send report to codecov.io
  #- bash <(curl -s https://codecov.io/bash)
  - codecov

notifications:
  email: false
