os: Visual Studio 2017

install:

environment:
  matrix:
    - platform: x86
      configuration: Static Debug
    - platform: x86
      configuration: Static Release
    - platform: x86
      configuration: Dynamic Debug
    - platform: x86
      configuration: Dynamic Release
    - platform: x64
      configuration: Static Debug
    - platform: x64
      configuration: Static Release
    - platform: x64
      configuration: Dynamic Debug
    - platform: x64
      configuration: Dynamic Release

matrix:
  fast_finish: false

before_build:
  - git submodule update --init --recursive
  - cd vendor\googletest\googletest
  - cmake .
  - devenv.exe gtest.sln /Build /SolnConfigName Debug|Win32
  - devenv.exe gtest.sln /Build /SolnConfigName Release|Win32
  - cd ..\..\..\
  
build:
  parallel: true
  project: build\visualstudio\wepp.sln
  verbosity: minimal
  
after_build:
    - bin\test.exe