os: Visual Studio 2017

install:

environment:
  matrix:
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Debug

matrix:
  fast_finish: false

before_build:
  - git submodule update --init --recursive
  - mkdir build2
  - cd build2
  - cmake .
  - cmake --build .
  - cd ..
  
build:
  parallel: true
  project: build2\wepp.sln
  verbosity: minimal
  
after_build:
    - bin\test.exe