os: Visual Studio 2017

install:

environment:
  matrix:
    - platform: x86
      configuration: Static Debug
    - platform: x86
      configuration: Static Release
    - platform: x86
      configuration: Dynamic Debug
    - platform: x86
      configuration: Dynamic Release
    - platform: x64
      configuration: Static Debug
    - platform: x64
      configuration: Static Release
    - platform: x64
      configuration: Dynamic Debug
    - platform: x64
      configuration: Dynamic Release

matrix:
  fast_finish: false

build:
  parallel: true
  project: build\visualstudio\wepp.sln
  verbosity: minimal
  
after_build:
    - bin\test.exe