os: Visual Studio 2017

configuration:
  - Debug
  - Release
platform:
  - Win32

matrix:
  fast_finish: false

before_build:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake ../
  - cd ..
  
build:
  parallel: true
  project: build\wepp.sln
  verbosity: minimal

for:
-
  matrix:
    only:
      - configuration: Release
        platform: Win32
  before_build:
    - echo "Not building release."
  
after_build:
    - bin\test.exe