os: Visual Studio 2017

install:

configuration:
  - Debug
  - Release
platform:
  - Win32

matrix:
  fast_finish: false

before_build:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake ../
  - cmake --build . --target complete
  - cd ..
  
build:
  parallel: true
  project: build2\wepp.sln
  verbosity: minimal
  
after_build:
    - bin\test.exe